{% set name = "tagmaps" %}
{% set version = "0.17.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c65ed1c7bcc5e1fa132b7656cf54d4f2e5ffd4b5d5d56ada26ee43ff93b362f5

build:
  noarch: python
  number: 0
  entry_points:
    - tagmaps = tagmaps.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - shapely
    - fiona
    - pandas >=0.24.2
    - pyproj >=1.9.6
    - numpy
    - matplotlib
    - emoji >=0.5.1
    - cython
    - hdbscan >=0.8.20
    - gdal
    - attrs
    - seaborn
    - descartes
    - regex
    - scipy

test:
  imports:
    - tagmaps
  commands:
    - tagmaps --help

about:
  home: https://github.com/Sieboldianus/TagMaps
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.md
  summary: Tag Clustering for Tag Maps
  description: |
    Perform tag clustering from spatially referenced and tagged records.
    TagMaps performs itemized or global clustering based on a list of records with
    multiple tags (or emoji) attached. Utilizes HDBSCAN for determining cluster
    results at specific (optional user defined) distance. Tags, Locations and
    Emoji are processed in descending order of global occurence, alpha
    shapes are generated for cluster point clouds. Produces two output
    shapefiles with cluster shapes that can be visualized, e.g. in ESRI ArcGIS.

extra:
  recipe-maintainers:
    - Sieboldianus
