{% set name = "tagmaps" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8db5a6022e8123fe50340aa7afeac6cf46f501f5cdbfb2fcdba05350f5575f0

build:
  noarch: python
  number: 0
  entry_points:
    - tagmaps = tagmaps.__main__:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python>=3.7
    - pip
  run:
    - python>=3.7
    - shapely
    - fiona==1.8.22 # pin until fiona-feedstock/issues/213 is solved
    - pandas>=0.24.2
    - pyproj>=2.0.0
    - numpy
    - matplotlib-base>=3.0.0
    - emoji>=2.0.0
    - cython
    - hdbscan>=0.8.20
    - gdal>3.4.1
    - seaborn
    - regex
    - scipy
    - joblib

test:
  imports:
    - tagmaps
  commands:
    - tagmaps --help

about:
  home: https://github.com/Sieboldianus/TagMaps
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.md
  summary: Tag Clustering for Tag Maps
  description: |
    Perform tag clustering from spatially referenced and tagged records.
    TagMaps performs itemized or global clustering based on a list of records with
    multiple tags (or emoji) attached. Utilizes HDBSCAN for determining cluster
    results at specific (optional user defined) distance. Tags, Locations and
    Emoji are processed in descending order of global occurence, alpha
    shapes are generated for cluster point clouds. Produces two output
    shapefiles with cluster shapes that can be visualized, e.g. in ESRI ArcGIS.

extra:
  recipe-maintainers:
    - Sieboldianus
