travis:
  secure:
    BINSTAR_TOKEN: C9Sw8KXnwezDwlnZq+vhhBqrDNDlVhMj621l3kd/yp2RlREe/NXMhPof+VljbkhzU5cVcRL55kCpDSyX6GVkq3MvPwKkamaReZjvnOJNIbo/pm+Nn/ihwxb+fdxOOe3zZx4tx9FvWdIvVq9nuWT9+7hflBGxrwPERLB6bnEaNcD9QFcOViCrnKd/EaNV3CItGM34ZIkdK0xi9Gv3X6nYdwsMRn85hwEpIlhVoa6BSy4SUt7H5AXc4AMxQ8J2w9b7T9INweVWIT1mGe5/Zflmgtb0Lc/NRWxGYzNM1jUIZ9wwjBGcAsm21Ep7SGWSz5rQkzvRODlXPHIyWGNASVD99SsAnZk6dvpowYdk2Lm78wyk04K06rkEpeu5FDb7Kj/q8AvtRSwBpHriiXSt9hKXM1szzBWQaIKteBGxgLwK5zWLh2ez/4ODbuJnr6xXgx3Lqogg7KOjwb21h9846L8XQe0QxHmTWw2FmCtfSE14mhQHZm4N3zZulEJh3MxIR12LcKqYF4u+fkUeKEtnO52B9sNOUYtB+7qG+sD/GrZLk3H7bvv+4ntW2DCXNqLlRbJG6iX+QKWpCxWF3idZSOi5Qvn09/m4QNUY+drssGfHMSVsIlXnJSptAw88q5+300cuDT3BJPsQYuyi3EQULqSCNBMuV+vjnCGloiYEZe6pD3M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
